version: '3.9'

services:
  realworld_rust_axum_sqlx_postgres:
    container_name: realworld_rust_axum_sqlx_postgres
    image: postgres:latest
    restart: always
    env_file:
      - ../.env
      - ../.env.docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"