[package]
name = "bluetooth-phind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.11.5"
tokio = { version = "1", features = ["full"] }
uuid = "1.7.0"
rand = "0.8"